apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  namespace: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: s21aht/todo-backend:latest
          ports:
            - containerPort: 3000
          env:
            - name: PG_HOST
              value: "postgres"
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: PG_USER
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: PG_PASSWORD
            - name: PG_DATABASE
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: PG_DATABASE
---
apiVersion: v1
kind: Service
metadata:
  name: todo-backend
  namespace: todo-app
spec:
  # type: NodePort
  type: LoadBalancer
  selector:
    app: todo-backend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
